const STRINGS = {
	USERNAME: "Username",
	OPRATIONNAME: "Operations",
	ADD_USER:"Add User",
	USER:'Users',
	OPRATION:"Operation List",
	REMEMBER_ME: "Remember Me",
	PASSWORD: "Password",
	FIRSTNAME: "First Name",
	FULLNAME: "Full Name",
	LASTNAME: "Last Name",
	EMAIL: "Email",
	ADDRESS: "Address",
	INTRODUCTION: "Describe Yourself",
	COUNTRY: "Country",
	PROVINCE: "Province",
	EDUCATION: "Education",
	CITY: "City",
	INTERESTS: "Interests",
	CERTIFICATE: "certificate",

	ITEM_DASHBOARD: "Item Dashboard",
	MANAGE_TEACHER: "Manage Teacher",
	STUDENTS: "Students",
	MANAGE_TEACHER_CREATE: "Create New Teacher",
	TEACHER_PROFILE: "Teacher Profile",
	TEACHER_DASHBOARD: "Dashboard",
	TEACHER_STUDENT_PROFILE_VIEW: "Student Profile",

	INSTITUTE_PROFILE: "Institute Profile",
	INSTITUTE_SETTINGS: "Settings",
	MANAGE_STUDENTS: "Manage Users",
	MANAGE_OPRATION: "Operations",
	MANAGE_OPRATION_CREATE: "Add Operation",
	MANAGE_OPRATION_UPDATE: "Update Operation",
	INSTITUTE: "Institute Name",

	FINANCE: "Finance",
	REQUESTS: "Requests",
	REGISTRATION_REQUEST: "Registration",
	COURSE_REQUEST: "Course",
	COUPONS: "Coupons",
	COUPONS_CREATE: "Generate New Coupons",
	ENROLLED_STUDENTS: "Enrolled Students",
	EARNINGS: "Earnings",
	VIEW_EARNINGS: "Earnings",
	STUDENTS_EARNINGS: "Earnings",
	COURSES: "Manage Trucks",
	COURSE_VIEW: "View Course ",
	NEW_COURSE: "Create New Course",
	COURSE_NAME: "Enter Course Name",
	COURSE_SUBTITLE: "Enter Course Subtitle",
	CATEGORY: "Select",

	STUDENT_PROFILE: "Student Profile",
	STUDENT_DASHBOARD: "Dashboard",
	STUDENT_ASSIGNMENTS: " Assignment",
	STUDENT_QUIZZES: " Quizzes",
	STUDENT_COURSE_VIEW: "Lectures",
	STUDENT_GRADING: "Grading",
	STUDENT_GRADE_ASSIGNMENTS: "Assignment",
	STUDENT_GRADE_QUIZZES: "Quizzes",
	STUDENT_ENROLLED_COURSES: "Operations",
	AGE: "Age",
	PHONE: "Phone No",
};

export default STRINGS;
