import PATH from "./Path";

export const backPaths: { [key: string]: string } = {
	[PATH.COURSE_VIEW]: PATH.COURSES,
	[PATH.COURSE_VIEW_STUDENT]: PATH.STUDENT_COURSES_LIST,
	[PATH.STUDENTS_EARNINGS]: PATH.EARNINGS,
	[PATH.VIEW_EARNINGS]: PATH.EARNINGS,
	[PATH.MANAGE_TEACHER_CREATE]: PATH.MANAGE_TEACHER,
	[PATH.MANAGE_OPRATION_CREATE]: PATH.MANAGE_OPRATION,
	[PATH.NEW_COURSE]: PATH.COURSES,
	[PATH.TEACHER_STUDENT_PROFILE_VIEW]: PATH.STUDENTS,
};
